# Generated by Django 5.2.5 on 2026-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_counselorfeedback_counselorprofileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='actual_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
