# Generated by Django 5.2.5 on 2026-03-06 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_wellnesstip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='activity_type',
            field=models.CharField(choices=[('counselor_approved', 'Counselor Approved'), ('counselor_rejected', 'Counselor Rejected'), ('user_added', 'User Added'), ('counselor_added', 'Counselor Added'), ('admin_added', 'Admin Added'), ('user_registered', 'User Registered'), ('user_login', 'User Login'), ('email_verified', 'Email Verified'), ('appointment_booked', 'Appointment Booked'), ('appointment_cancelled', 'Appointment Cancelled'), ('first_chatbot_use', 'First Chatbot Use')], max_length=25),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
