# Generated by Django 5.2.5 on 2026-03-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_recentactivity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='activity_type',
            field=models.CharField(choices=[('counselor_approved', 'Counselor Approved'), ('counselor_rejected', 'Counselor Rejected'), ('user_added', 'User Added'), ('counselor_added', 'Counselor Added'), ('admin_added', 'Admin Added'), ('user_registered', 'User Registered'), ('user_login', 'User Login'), ('email_verified', 'Email Verified'), ('appointment_booked', 'Appointment Booked'), ('appointment_cancelled', 'Appointment Cancelled'), ('first_chatbot_use', 'First Chatbot Use'), ('feedback_sent', 'Feedback Sent')], max_length=30),
        ),
    ]
